# Generated by Django 5.0.6 on 2024-07-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="first_name",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.IntegerField(default=0),
        ),
    ]
